apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-station
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tage
  source:
    repoURL: https://github.com/openshift-app-service-poc/helm-station-config.git
    targetRevision: HEAD
    path: stage/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true